name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test
    
    

    - run: docker  build --no-cache -t sysinfo-api:0.0.2 . 
    - run: docker tag sysinfo-api:0.0.2 ${{secrets.DOCKER_USER}}/sysinfo-api:0.0.2
    - run: docker logout
    - name: connect docker
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - run: docker push ${{secrets.DOCKER_USER}}/sysinfo-api:0.0.2

    - name: Heroku login credentials
      run: |
        cat > ~/.netrc <<EOF
          machine api.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
          machine git.heroku.com
            login $HEROKU_EMAIL
            password $HEROKU_API_KEY
        EOF
      env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}

    - run: docker tag sysinfo-api:0.0.2 registry.heroku.com/sysinfo-api-popoleii/web
    - run: docker push registry.heroku.com/sysinfo-api-popoleii/web
    - run: heroku container:release web -a sysinfo-api-popoleii
